### ISSUE TITLE
Impala cannot be used for evaluator

### ISSUE THREAD

**Issue by X-I-O-N** [spring01/drlbox#2]
Hey, any plans to support Impala for the make_evaluator ?

Doesn't seem to be in the dic. If there is a workaround, I'd appreciate it.

Love the project!

**Comment by spring01** [comment]
Hi, I think it'll be equivalent to using the plain actor-critic evaluator `make_evaluator('ac')` as they use the same form of neural net output.

**Comment by X-I-O-N** [comment]
worked! Thanks!
